- Developer:
    - Github:
        - icon: github.svg
          href: https://github.com

- Social:
    - Reddit:
        - icon: reddit.svg
          href: https://reddit.com
    - Twitter:
        - icon: twitter.svg
          href: https://twitter.com

- Entertainment:
    - Bilibili:
        - abbr: BL
          href: https://bilibili.com
