- Static:
    - OpenWRT:
        href: https://lede.yzld2002.cn
        icon: openwrt.svg
    - PVE:
        href: https://pve.yzld2002.cn
        icon: proxmox.svg
    - switch:
        href: https://switch.yzld2002.cn
        abbr: TP
    - traefik:
        href: https://traefik.yzld2002.cn
        icon: traefik.svg
        widget:
          type: traefik
          url: https://traefik.yzld2002.cn

- Docker:
    - Dockge:
        href: https://dockge.yzld2002.cn
        icon: dockge-light.svg
        server: my-docker
        container: dockge-dockge-1
