---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short

- resources:
    label: System
    cpu: true
    memory: true
    uptime: true

- resources:
    label: Strorage
    disk:
      - /

- search:
    provider: google
    target: _blank
